version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/udevslab
    networks:
      - app_network
    depends_on:
      - mongodb

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/udevslab
    networks:
      - app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "27018:27018"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
